name: Run CLI on Push to Main

on:
  push:
    branches:
      - main

jobs:
  run-cli:
    runs-on: ubuntu-latest
    env:
      COG_TOKEN: ${{ secrets.COG_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run CLI
      run: |
        echo $COG_TOKEN
        make push
